### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by ilyalesik** [tverio/community#4]

**Comment by ilyalesik** [comment]
@all-contributors please add @ilyalesik  for code

**Comment by ilyalesik** [comment]
@all-contributors please add @jonny-novikov  for code, review, eventOrganizing, add @ilyalesik for code, review, add @sponomarev for code, add @lexich for code, add @kalginnick for code, add @Slavenin for code

**Comment by ilyalesik** [comment]
@all-contributors please add @jonny-novikov for code, review, eventOrganizing 
@all-contributors please add @ilyalesik for code, review
@all-contributors please add @sponomarev for code
@all-contributors please add @lexich for code
@all-contributors please add @kalginnick for code
@all-contributors please add @Slavenin for code

**Comment by ilyalesik** [comment]
@all-contributors please add @jonny-novikov for code, review, eventOrganizing

**Comment by ilyalesik** [comment]
@all-contributors please add @ilyalesik for code, review

**Comment by ilyalesik** [comment]
@all-contributors please add @ilyalesik for code, review

**Comment by ilyalesik** [comment]
@all-contributors please add @sponomarev for code

**Comment by ilyalesik** [comment]
@all-contributors please add @lexich for code

**Comment by ilyalesik** [comment]
@all-contributors please add @kalginnick for code

**Comment by ilyalesik** [comment]
@all-contributors please add @Slavenin for code

**Comment by ilyalesik** [comment]
@all-contributors please add @AlexanderShushunov for ideas, eventOrganizing

**Comment by ilyalesik** [comment]
@all-contributors please add @jonny-novikov for ideas

**Comment by ilyalesik** [comment]
@all-contributors please add @jonny-novikov for ideas

**Comment by jonny-novikov** [comment]
@ilyalesik Well done! That's great to see on the start page!
